# Generated by Django 4.0.3 on 2022-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
